name = "discord-invite-widget"
main = "src/worker.ts"
compatibility_date = "2023-06-15"

[placement]
mode = "smart"

[env.development.vars]
ENVIRONMENT = "development"

[env.development]
name = "discord-invite-widget-cf-workers-development"

[env.production]
name = "discord-invite-widget-cf-workers-production"

[env.production.vars]
ENVIRONMENT = "production"
