name = "discord-invite-widget"
main = "src/worker.ts"
compatibility_date = "2023-06-15"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

[env.development.vars]
ENVIRONMENT = "development"

[env.production.vars]
ENVIRONMENT = "production"
