name: CI (Typecheck & Lint & Deploy)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Linting check
        run: npm run lint

      - name: Prettier check
        run: npm run prettier:check

      - name: Typecheck app
        run: npm run typecheck
